-- Premade categories so the app is usable right after its first run.
INSERT INTO categories (name_en, name_fr, type) VALUES
    ('Other', 'Autre', 'expense'),
    ('Gift', 'Cadeau', 'expense'),
    ('Animals', 'Animaux', 'expense'),
    ('Cash', 'Comptant', 'expense'),
    ('Culture', 'Culture', 'expense'),
    ('Business expense', 'Dépense d’entreprise', 'expense'),
    ('Education', 'Éducation', 'expense'),
    ('Groceries', 'Épicerie', 'expense'),
    ('Leisure', 'Loisir', 'expense'),
    ('Rent', 'Loyer', 'expense'),
    ('Home', 'Maison', 'expense'),
    ('Restaurant', 'Restaurant', 'expense'),
    ('Health', 'Santé', 'expense'),
    ('Sports', 'Sport', 'expense'),
    ('Tech', 'Tech', 'expense'),
    ('Transport', 'Transport', 'expense'),
    ('Work', 'Travail', 'expense'),
    ('Vacation', 'Vacance', 'expense'),
    ('Clothing', 'Vêtement', 'expense'),
    ('Furniture', 'Ameublement', 'expense'),
    ('Daycare', 'Garderie', 'expense'),
    ('Insurance', 'Assurance', 'expense'),
    ('Subscriptions', 'Abonnements', 'expense'),
    ('Donations', 'Dons', 'expense'),
    ('Unknown', 'Inconnu', 'expense'),
    ('Business income', 'Revenu d’entreprise', 'income'),
    ('Salary', 'Salaire', 'income'),
    ('Government', 'Gouvernement', 'income'),
    ('TFSA', 'CELI', 'transfer'),
    ('RRSP', 'REER', 'transfer'),
    ('FHSA', 'CELIAPP', 'transfer'),
    ('Credit card', 'Carte de crédit', 'transfer'),
    ('Transfer', 'Transfert', 'transfer');
