name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Run linting
        working-directory: frontend
        run: npm run lint

      - name: Run unit tests
        working-directory: frontend
        run: echo "Running unit tests..." && echo "No tests implemented yet."

      - name: Run UI tests
        working-directory: frontend
        run: echo "Running UI tests..." && echo "No tests implemented yet."
